spring:
  datasource:
    name: sa
    password: sa
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE

  application:
    name: webshop

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml